### ISSUE TITLE
`version` dimension in CI build matrix seems to have no effect

### ISSUE THREAD

**Issue by kyllingstad** [viproma/cppfmu#10]
The CI build matrix contains a `version` dimension with one element: `"1.0"`. As far as I can tell, this gets passed to the `--version` switch of `conan create`, which is used to specify the package version when no version is given in the `conanfile`. But we *do* provide a version in `conanfile.py` (or more precisely, in `version.txt`), so the version switch apparently has no effect.

**Comment by kyllingstad** [comment]
@joakimono, can you confirm the above diagnosis? Or have I misunderstood how this works?

**Comment by joakimono** [comment]
I can confirm. This is a remnant from recipe patterns that can build various versions. It should be removed.

**Comment by kyllingstad** [comment]
Fixed by PR #11.
