### ISSUE TITLE
Conditionally support additional FMI functions

### ISSUE THREAD

**Issue by markaren** [viproma/cppfmu#4]
`cppfmu` does not support some functions like get/set state, serialize/deserialize state. I propose that there should be a compiler flag conditionally enabling support for these functions.

**Comment by kyllingstad** [comment]
Agreed. Actually, I think it doesn't even have to be a compiler flag. The FMI functions should simply be implemented in `fmi_functions.cpp` and added as new virtual functions in `SlaveInstance`. The `SlaveInstance` methods should then have a no-op or error-producing default implementation so they don't have to be overridden by client model code unless they're really needed.

Do you have an urgent need for any of the missing functions? If so, I can try to set aside some time to add them.

**Comment by markaren** [comment]
I have already added these functions in our code (PythonFMU and FMI4j), but if it was added upstream we could depend on `cppfmu` as a git `submodule`
