### ISSUE TITLE
componentEnvironment points to an FMU-Internal data structure

### ISSUE THREAD

**Issue by dirk-runge** [viproma/cppfmu#5]
The componentEnvironment pointer passed to the `logger` and `stepFinished` callbacks is wrong. You must pass the pointer given by the simulation environment via the `componentEnvironment` pointer in the `fmi2CallbackFunctions` structure.

Change 

`logger{this, cppfmu::CopyString(memory, instanceName), callbackFunctions, loggerSettings}`

to

`logger{callbackFunctions.componentEnvironment, cppfmu::CopyString(memory, instanceName), callbackFunctions, loggerSettings}`

**Comment by kyllingstad** [comment]
Thanks for the bug report (and the solution!). I've pushed a fix to `master` now, can you check whether it fixes the problem for you?

**Comment by dirk-runge** [comment]
Yes, that fixes the problem. Many thanks for the fix and for this great project!
